### ISSUE TITLE
Same version as cropper

### ISSUE THREAD

**Issue by jagomf** [anilmaurya/ember-cli-cropper#1]
I wonder if it would be interesting to keep same version number as Feng Yuan Chen's cropper package. It would help make sure of which version of the cropper we are using, even if we are using ember-cli-cropper.

Right now, I want to use cropper's v2.3.0, but I have to choose ember-cli-cropper v0.0.5... a bit messy, isn't it?

**Comment by anilmaurya** [comment]
Yeah, sounds interesting.Are you willing to submit a pull request for the same.

**Comment by jagomf** [comment]
Are you using version 0.7.9 of the cropper for any reason? Have you tried any more recent version?

**Comment by anilmaurya** [comment]
I have not tried recent versions, I think recent version should work.
